### ISSUE TITLE
Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by Huntk23** [kspearrin/Visual-Studio-jQuery-Code-Snippets#21] opened 2016-04-08 14:52 UTC
Hi,

When I installed update 2 my jQuery snippets no longer work. I see the jQuery snippets in the manager and can see just the jQuery folder in the IntelliSense but when I choose it, nothing is in it. I've attempted a re-install with no success. My activity log shows this error when I try typing after the jQuery folder is selected in IntelliSense:

System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.Snippets.SnippetPicker.OnTypedChar(Char typedChar, Boolean provisionalText)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.Snippets.SnippetPicker.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

**Comment by kspearrin** [comment] 2016-04-08 14:57
I have not installed update 2 yet myself. I will try to do that soon to see if I can reproduce. It is not immediately apparent to me what the issues is at the moment. Let me know if you find a solution in the meantime.

**Comment by kspearrin** [comment] 2016-04-14 18:21
I've moved to update 2 and did not have any issues regarding the extension.

**Comment by kspearrin** [comment] 2016-05-05 20:04
Closing this since I cannot reproduce.

**Closed by kspearrin** 2016-05-05 20:04 UTC
